services:
  - type: web
    name: group-project-petly-be
    env: node
    plan: free
    repo: https://github.com/Max-Loktionov/petly-be
    branch: main
    buildCommand: yarn
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
      - key: DB_HOST
      - key: SECRET_KEY
